ballerina-platform/module-ballerina-cache

cache-ballerina/src/cache/cache.bal, cache-native/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/Cache.java
=> Add missed packages

cache-ballerina/build.gradle
$Subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Improve the build command

cache-ballerina/Ballerina.toml, cache-ballerina/build.gradle
=> Add dependencies in the toml file

cache-ballerina/build.gradle
=> Add task dependency

cache-ballerina/src/cache/tests/unit-test/test.bal
=> Refactor unit tests

README.md
=> Remove Ballerina performance link from README

cache-ballerina/src/cache/abstract_cache.bal, cache-ballerina/src/cache/abstract_eviction_policy.bal, cache-ballerina/src/cache/cache.bal, cache-ballerina/src/cache/lru_eviction_policy.bal, cache-ballerina/src/cache/tests/unit-test/test.bal
=> Fix the ballerina lang breaking changes

cache-native/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/Cache.java
=> Migrate jBallerina Runtime APIs

.github/workflows/pull-request.yml, cache-ballerina/src/cache/abstract_cache.bal, cache-ballerina/src/cache/abstract_eviction_policy.bal, cache-ballerina/src/cache/cache.bal, cache-ballerina/src/cache/cache_errors.bal, cache-ballerina/src/cache/linked_list.bal, cache-ballerina/src/cache/lru_eviction_policy.bal
=> Fix isolated changes

.github/workflows/publish-release.yml, build.gradle, cache-ballerina/build.gradle
=> Add GitHub release workflow

build.gradle
=> Remove unwanted maven repository

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, README.md, build.gradle, cache-ballerina/Ballerina.toml, cache-ballerina/build.gradle, cache-native/build.gradle, cache-native/src/main/java/module-info.java, gradle.properties
=> Migrate cache module to JDK11

README.md
=> Change build URLs in the README

cache-native/src/main/java/module-info.java, cache-native/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/Cache.java
Refactor ballerina runtime api usages
=> Migrate ballerina runtime apis

cache-ballerina/src/cache/cache.bal, cache-ballerina/src/cache/linked_list.bal, cache-native/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/Lock.java
=> Fix the concurrent behaviour issue

.github/workflows/build-master.yml, README.md
=> Update README Content

gradle.properties
=> Upgrade dependencies version

.github/workflows/build-master.yml, README.md
=> Update repository dispatch path

build.gradle, cache-ballerina/Ballerina.toml, cache-ballerina/build.gradle, cache-ballerina/tests/test.bal, gradle.properties
=> Remove transitive dependencies

cache-ballerina/cache.bal, cache-ballerina/linked_list.bal
$Subject
Fixes [#630](https://github.com/ballerina-platform/ballerina-standard-library/issues/630)
=> Fix concurrent behavior issue

cache-ballerina/cache.bal, cache-ballerina/cache_errors.bal
=> Remove Log API methods 

cache-ballerina/cache_errors.bal, cache-ballerina/tests/test.bal
=> Make the ballerina-lang syntax changes

build.gradle, cache-ballerina/Ballerina.toml, cache-ballerina/Package.md, cache-ballerina/build.gradle, cache-ballerina/tests/test.bal, gradle.properties, settings.gradle
=> Migrate runtime:sleep to lang.runtime:sleep

build.gradle
=> Remove runtime dependency from the build.gradle

cache-ballerina/cache.bal
=> Handle the error in the scheduler initialization

cache-ballerina/build.gradle
Update ballerina command to bal command
issue https://github.com/ballerina-platform/ballerina-lang/issues/27680
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR …
=> Update ballerina command to bal command

cache-ballerina/cache.bal, cache-ballerina/linked_list.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

cache-ballerina/Ballerina.toml, cache-ballerina/Dependencies.toml, cache-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

cache-ballerina/build.gradle
=> Improve revertTomlFile task

build.gradle, cache-ballerina/Dependencies.toml, cache-ballerina/build.gradle, cache-ballerina/cache_errors.bal, gradle.properties
=> Remove log dependency

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, README.md, cache-ballerina/build.gradle, cache-ballerina/tests/test.bal
=> Generate code coverage report

cache-ballerina/build.gradle
=> Avoid runnig tests twice when publishing

README.md, cache-ballerina/Package.md
=> Update doc links

cache-ballerina/Package.md
=> Change module to package

README.md
=> Change module to package in the README

.github/workflows/publish-release.yml, build.gradle, cache-ballerina/build.gradle, gradle.properties
=> Enable Publishing to Ballerina Central on Release

build.gradle, cache-ballerina/build.gradle
=> Re-order build tasks to enable publishing to central

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, cache-ballerina/build.gradle
=> Remove publishing testable jar and exec artifacts

cache-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

cache-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
=> Add -c flag to build command

cache-ballerina/abstract_cache.bal, cache-ballerina/cache.bal, cache-ballerina/tests/test.bal
=> Change method signature time prams type to decimal

cache-ballerina/cache.bal, cache-ballerina/tests/test.bal, gradle.properties
=> Update task-related function with latest API changes

cache-ballerina/cache.bal
=> Fix type cast error in the relational operators

.github/workflows/central-publish.yml, cache-ballerina/build.gradle
=> Add workflow to publish to central

build.gradle, cache-ballerina/build.gradle
=> Strip stdlib dependency version

.github/workflows/central-publish.yml, README.md, cache-ballerina/build.gradle
$Subject
Related issue: [#1247](https://github.com/ballerina-platform/ballerina-standard-library/issues/1247)
=> Fix the Ballerina.toml updating before the Ballerina push

build-config/checkstyle/build.gradle, build.gradle, cache-ballerina/build.gradle, gradle.properties
Standardize build script of Ballerina module
=> Apply Gradle Ballerina plugin for Ballerina module build script

README.md, cache-ballerina/Module.md, cache-ballerina/Package.md, cache-ballerina/cache.bal
=> Improve API Docs

cache-ballerina/build.gradle
Remove overriding testCoverageParam and use the value from the gradle plugin.
=> Remove overriding testCoverageParam

cache-ballerina/Module.md
=> Remove invalid Reference to the functions

cache-ballerina/cache_errors.bal, cache-ballerina/tests/test.bal, cache-native/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/concurrentlinkedhashmap/ConcurrentLinkedHashMap.java, cache-native/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/concurrentlinkedhashmap/LinkedDeque.java, cache-native/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/concurrentlinkedhashmap/Weighers.java
$Subject
This pr depends on [#176](https://github.com/ballerina-platform/module-ballerina-task/pull/176)
Related issue: [#1425](https://github.com/ballerina-platform/ballerina-standard-library/issues/1425)
=> Improve the test coverage

cache-ballerina/cache.bal
$Subject
fixes:  [1551](https://github.com/ballerina-platform/ballerina-standard-library/issues/1551)
=> Add full stop in the description

ballerina/tests/test.bal, native/src/main/java/io/ballerina/stdlib/cache/nativeimpl/Cache.java
$Subject
Related issue: [1677](https://github.com/ballerina-platform/ballerina-standard-library/issues/1677)
=> Get ceil value of the eviction count

.github/workflows/publish-release.yml, ballerina/Dependencies.toml, ballerina/build.gradle, build-config/resources/Ballerina.toml, gradle.properties
$Subject 
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1746
=> Make the Ballerina project tooling friendly

ballerina/Dependencies.toml, ballerina/cache.bal, ballerina/tests/test.bal
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2312
=> Improve cache code quality

ballerina/Module.md, ballerina/cache.bal, docs/spec/spec.md
$Subject
Fixes: [#2325](https://github.com/ballerina-platform/ballerina-standard-library/issues/2325)
=> Add cache module specification

load-tests/order_management_service/deployment/ingress.yaml
=> Remove tls configuration from ingress file

ballerina/Module.md
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2558
=> Update Module.md file

.github/pull_request_template.md, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2483
=> Update trivy action to scan lib directory and update PR template

gradle.properties, native/src/main/java/io/ballerina/stdlib/cache/nativeimpl/Cache.java
=> Update lang version to 2201.0.1

ballerina/Dependencies.toml, gradle.properties
=> Update dependencies' versions to the latest timestamp

docs/spec/spec.md
=> Update the content and sub-heading style

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/cache/compiler/CompilerPluginTest.java, compiler-plugin-tests/src/test/resources/diagnostics/sample4/Ballerina.toml, compiler-plugin-tests/src/test/resources/diagnostics/sample4/main.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/cache/compiler/CacheConfigValidator.java
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3328
=> Add compiler plugin testcase to validate passing config variables

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/cache/compiler/CompilerPluginTest.java, compiler-plugin-tests/src/test/resources/diagnostics/sample5/Ballerina.toml, compiler-plugin-tests/src/test/resources/diagnostics/sample5/main.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/cache/compiler/CacheConfigValidator.java
$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3386
=> Fix the compiler plugin issue

ballerina/Dependencies.toml, gradle.properties
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3315
=> Update task package version

README.md, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/Package.md, build-config/resources/Ballerina.toml, changelog.md, docs/spec/spec.md, gradle.properties
$Subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
=> Update slack link and versions

ballerina/Dependencies.toml, gradle.properties
=> Update constraint version

.github/workflows/build-timestamped-master.yml
=> Ignore load test results in build

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
=> Update versions for type-reference-support 

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update lang and dependecy versions

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, README.md, build-config/checkstyle/build.gradle, compiler-plugin-tests/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, native/build.gradle, native/src/main/java/io/ballerina/stdlib/cache/nativeimpl/concurrentlinkedhashmap/ConcurrentLinkedHashMap.java, native/src/main/java/io/ballerina/stdlib/cache/nativeimpl/concurrentlinkedhashmap/Linked.java, native/src/main/java/io/ballerina/stdlib/cache/nativeimpl/concurrentlinkedhashmap/LinkedDeque.java, native/src/main/java/io/ballerina/stdlib/cache/nativeimpl/concurrentlinkedhashmap/Weigher.java, settings.gradle
=> Migrate to Java 17

.github/workflows/build-with-bal-test-graalvm.yml
=> Change GraalVm build to Java 17

.github/workflows/build-with-bal-test-graalvm.yml
=> Use master branch for GraalVm

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, gradle.properties
=> Update Java version to 17.0.7 at workflows

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> Update versions for U11

ballerina/Dependencies.toml, ballerina/build.gradle, build.gradle, gradle.properties, settings.gradle
=> Update Ballerina Gradle Plugin Version and Build Scripts
